### ISSUE TITLE
关于“clip_contours_by_map”裁剪栅格数据的问题

### ISSUE THREAD

**Issue by tiazii** [cnmetlab/cnmaps#107]
您好，我想问一下，假如我要使用"clip_contours_by_map"方法对0.5°空间分辨率的数据进行掩膜裁剪，裁剪后的数据范围是与边界贴合的。那么位于裁剪边界的栅格数据是被插值处理还是把边界外的部分数据删掉了呢？

**Comment by Clarmy** [comment]
@tiazii matplotlib 的 contour 和 contourf 图像是经过插值的，所以你的问题的简单答案是 **被插值了** 。

**Comment by tiazii** [comment]
好的，我明白了，谢谢您！





------------------ 原始邮件 ------------------
发件人: Wentao Li ***@***.***&gt;
发送时间: 2023年8月15日 14:21
收件人: cnmetlab/cnmaps ***@***.***&gt;
抄送: tiazii ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [cnmetlab/cnmaps] 关于“clip_contours_by_map”裁剪栅格数据的问题 (Issue #107)





 
@tiazii matplotlib 的 contour 和 contourf 图像是经过插值的，所以你的问题的简单答案是 被插值了 。
