### ISSUE TITLE
安装cnmaps后绘图报错（包版本：1.1.7）

### ISSUE THREAD

**Issue by ww15996472026** [cnmetlab/cnmaps#109]
**1、在进行合并边界（示例）操作时报错：**
```
jingjinji = beijing + tianjin + hebei
Traceback (most recent call last):

  Cell In[24], line 1
    jingjinji = beijing + tianjin + hebei

  File D:\anaconda\Lib\site-packages\cnmaps\maps.py:43 in __add__
    return self.union(other)

  File D:\anaconda\Lib\site-packages\cnmaps\maps.py:78 in union
    union_result = super().union(other)

  File D:\anaconda\Lib\site-packages\shapely\geometry\base.py:704 in union
    return geom_factory(self.impl['union'](self, other))

  File D:\anaconda\Lib\site-packages\shapely\topology.py:69 in __call__
    product = self.fn(this._geom, other._geom, *args)

OSError: exception: access violation reading 0x00000000000001A4
```

**2、安装cnmaps后，原本能正常出图的代码，在运行matplotlib绘图时同样报错：**
```
fig_ax1.set_extent([leftlon,rightlon,lowerlat,upperlat],crs=ccrs.PlateCarree())
Traceback (most recent call last):

  Cell In[26], line 1
    fig_ax1.set_extent([leftlon,rightlon,lowerlat,upperlat],crs=ccrs.PlateCarree())

  File D:\anaconda\Lib\site-packages\cartopy\mpl\geoaxes.py:858 in set_extent
    projected = self.projection.project_geometry(domain_in_crs, crs)

  File D:\anaconda\Lib\site-packages\cartopy\crs.py:817 in project_geometry
    return getattr(self, method_name)(geometry, src_crs)

  File D:\anaconda\Lib\site-packages\cartopy\crs.py:823 in _project_line_string
    return cartopy.trace.project_linear(geometry, src_crs, self)

  File lib/cartopy/trace.pyx:585 in cartopy.trace.project_linear

  File D:\anaconda\Lib\site-packages\shapely\impl.py:37 in wrapper
    return func(*args, **kwargs)

  File D:\anaconda\Lib\site-packages\shapely\prepared.py:61 in covers
    return bool(self.impl['prepared_covers'](self, other))

  File D:\anaconda\Lib\site-packages\shapely\predicates.py:15 in __call__
    return self.fn(this._geom, other._geom, *args)

OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

![1](https://github.com/cnmetlab/cnmaps/assets/105007689/5069bb3f-dd5a-48e1-9f97-f02c0e6194df)

![3](https://github.com/cnmetlab/cnmaps/assets/105007689/27f22726-533f-4faf-9d96-b76996223134)

**Comment by Clarmy** [comment]
你好，请执行一下 `pip list` 看一下依赖包的版本信息。

**Comment by ww15996472026** [comment]
----------------------------- ---------------
aiobotocore                   2.4.2
aiofiles                      22.1.0
aiohttp                       3.8.3
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-catalogs             0.2.0
anaconda-client               1.12.0
anaconda-navigator            2.4.2
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         0.0
bleach                        4.1.0
bokeh                         3.2.1
boltons                       23.0.0
boto3                         1.24.28
botocore                      1.27.59
Bottleneck                    1.3.5
brotlipy                      0.7.0
build                         0.10.0
CacheControl                  0.13.1
Cartopy                       0.22.0
cdo                           1.6.0
cdsapi                        0.6.1
certifi                       2023.7.22
cf-xarray                     0.8.4
cffi                          1.15.1
cfgrib                        0.9.8.5
cftime                        1.6.2
chardet                       4.0.0
charset-normalizer            2.0.4
cleo                          2.0.1
click                         8.0.4
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   2.2.1
clyent                        1.2.2
cmaps                         2.0.1
cnmaps                        1.1.7
colorama                      0.4.6
colorcet                      3.0.1
comm                          0.1.2
conda                         23.7.4
conda-build                   3.26.0
conda-content-trust           0.2.0
conda_index                   0.2.3
conda-libmamba-solver         23.5.0
conda-pack                    0.6.0
conda-package-handling        2.2.0
conda_package_streaming       0.9.0
conda-repo-cli                1.0.41
conda-token                   0.4.0
conda-verify                  3.4.2
constantly                    15.1.0
contourpy                     1.0.5
cookiecutter                  1.7.3
crashtest                     0.4.1
cryptography                  41.0.2
cssselect                     1.1.0
cycler                        0.11.0
cytoolz                       0.12.0
daal4py                       2023.1.1
dask                          2023.6.0
datashader                    0.15.1
datashape                     0.5.4
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
distlib                       0.3.7
distributed                   2023.6.0
docstring-to-markdown         0.11
docutils                      0.18.1
dulwich                       0.21.6
eccodes                       1.6.0
entrypoints                   0.4
eofs                          1.4.0
et-xmlfile                    1.1.0
executing                     0.8.3
fastjsonschema                2.16.2
filelock                      3.12.4
findlibs                      0.0.5
fiona                         1.9.5
flake8                        6.0.0
Flask                         2.2.2
fonttools                     4.25.0
frozenlist                    1.3.3
fsspec                        2023.3.0
future                        0.18.3
gensim                        4.3.0
geocat.comp                   2023.10.0
geocat.viz                    2023.10.0
geojson                       3.0.1
geopandas                     0.14.0
glob2                         0.7
greenlet                      2.0.1
h5netcdf                      1.2.0
h5py                          3.7.0
HeapDict                      1.0.1
holoviews                     1.17.0
hvplot                        0.8.4
hyperlink                     21.0.0
idna                          3.4
imagecodecs                   2021.8.26
imageio                       2.26.0
imagesize                     1.4.1
imbalanced-learn              0.10.1
importlib-metadata            6.0.0
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
installer                     0.7.0
intake                        0.6.8
intervaltree                  3.1.0
ipykernel                     6.19.2
ipython                       8.12.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jaraco.classes                3.2.1
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jmespath                      0.10.0
joblib                        1.2.0
json5                         0.9.6
jsonpatch                     1.32
jsonpointer                   2.1
jsonschema                    4.17.3
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.6.3
jupyter_core                  5.3.0
jupyter-events                0.6.3
jupyter-server                1.23.4
jupyter_server_fileid         0.9.0
jupyter_server_ydoc           0.8.0
jupyter-ydoc                  0.2.4
jupyterlab                    3.6.3
jupyterlab-pygments           0.1.2
jupyterlab_server             2.22.0
jupyterlab-widgets            3.0.5
keyring                       24.2.0
kiwisolver                    1.4.4
lazy_loader                   0.2
lazy-object-proxy             1.6.0
libarchive-c                  2.9
libmambapy                    1.4.1
linkify-it-py                 2.0.0
llvmlite                      0.40.0
lmdb                          1.4.1
locket                        1.0.0
lxml                          4.9.2
lz4                           4.3.2
Markdown                      3.4.1
markdown-it-py                2.2.0
MarkupSafe                    2.1.1
matplotlib                    3.8.0
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdit-py-plugins               0.3.0
mdurl                         0.1.0
menuinst                      1.4.19
MetPy                         1.5.1
mistune                       0.8.4
mkl-fft                       1.3.6
mkl-random                    1.2.2
mkl-service                   2.4.0
more-itertools                8.12.0
mpmath                        1.3.0
msgpack                       1.0.3
multidict                     6.0.2
multipledispatch              0.6.0
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.4.0
nbclassic                     0.5.5
nbclient                      0.5.13
nbconvert                     6.5.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
netCDF4                       1.6.2
networkx                      3.1
nltk                          3.8.1
notebook                      6.5.4
notebook_shim                 0.2.2
numba                         0.57.0
numexpr                       2.8.4
numpy                         1.24.3
numpydoc                      1.5.0
openpyxl                      3.0.10
orjson                        3.9.9
packaging                     23.0
pandas                        1.5.3
pandocfilters                 1.5.0
panel                         1.2.1
param                         1.13.0
parameterized                 0.9.0
paramiko                      2.8.1
parsel                        1.6.0
parso                         0.8.3
partd                         1.2.0
pathlib                       1.0.1
pathspec                      0.10.3
patsy                         0.5.3
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
Pint                          0.22
pip                           23.2.1
pkginfo                       1.9.6
platformdirs                  3.10.0
plotly                        5.9.0
pluggy                        1.0.0
ply                           3.11
poetry                        1.6.1
poetry-core                   1.7.0
poetry-plugin-export          1.5.0
pooch                         1.4.0
poyo                          0.5.0
prometheus-client             0.14.1
prompt-toolkit                3.0.36
properscoring                 0.1
Protego                       0.1.16
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    8.0.0
pyarrow                       11.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.10.0
pycosat                       0.6.4
pycparser                     2.21
pyct                          0.5.0
pycurl                        7.45.2
PyDispatcher                  2.0.5
pydocstyle                    6.3.0
pyerfa                        2.0.0
pyflakes                      3.0.1
Pygments                      2.15.1
PyJWT                         2.4.0
pylint                        2.16.2
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyodbc                        4.0.34
pyOpenSSL                     23.2.0
pyparsing                     3.0.9
pyproj                        3.4.1
pyproject_hooks               1.0.0
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.0
pyshp                         2.3.1
PySocks                       1.7.1
pytest                        7.4.0
python-dateutil               2.8.2
python-json-logger            2.0.7
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.2
python-slugify                5.0.2
python-snappy                 0.6.1
pytoolconfig                  1.2.5
pytz                          2022.7
pyviz-comms                   2.3.0
PyWavelets                    1.4.1
pywin32                       305.1
pywin32-ctypes                0.2.0
pywinpty                      2.0.10
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.2
QtPy                          2.2.0
queuelib                      1.5.0
rapidfuzz                     2.15.1
regex                         2022.7.9
requests                      2.31.0
requests-file                 1.5.1
requests-toolbelt             1.0.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rope                          1.7.0
Rtree                         1.0.1
ruamel.yaml                   0.17.21
ruamel-yaml-conda             0.17.21
s3fs                          2023.3.0
s3transfer                    0.6.0
sacpy                         0.0.19
sacremoses                    0.0.43
scikit-image                  0.20.0
scikit-learn                  1.3.0
scikit-learn-intelex          20230426.121932
scipy                         1.10.1
Scrapy                        2.8.0
seaborn                       0.12.2
Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    68.0.0
Shapely                       1.8.5.post1
shellingham                   1.5.3
sip                           6.6.2
six                           1.16.0
smart-open                    5.2.1
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.3
spyder-kernels                2.4.3
SQLAlchemy                    1.4.39
stack-data                    0.2.0
statsmodels                   0.14.0
sympy                         1.11.1
tables                        3.8.0
tabulate                      0.8.10
TBB                           0.2
tblib                         1.7.0
tenacity                      8.2.2
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss2                      1.2.1
tldextract                    3.2.0
toml                          0.10.2
tomlkit                       0.12.1
toolz                         0.12.0
tornado                       6.3.2
tqdm                          4.65.0
traitlets                     5.7.1
transformers                  2.1.1
trove-classifiers             2023.9.19
Twisted                       22.10.0
twisted-iocpsupport           1.0.2
typing_extensions             4.7.1
uc-micro-py                   1.0.1
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.16
virtualenv                    20.24.5
w3lib                         1.21.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      2.2.3
whatthepatch                  1.0.2
wheel                         0.38.4
widgetsnbextension            4.0.5
win-inet-pton                 1.1.0
wrapt                         1.14.1
xarray                        2023.2.0
xhistogram                    0.3.2
xlrd                          2.0.1
xlwings                       0.29.1
xmca                          1.4.2.post2
xskillscore                   0.0.24
xyzservices                   2022.9.0
y-py                          0.5.9
yapf                          0.31.0
yarl                          1.8.1
ypy-websocket                 0.8.2
zict                          2.2.0
zipp                          3.11.0
zope.interface                5.4.0
zstandard                     0.19.0

**Comment by Clarmy** [comment]
包的依赖有点多，你可以尝试一下创建一个新的虚拟环境安装 cnmaps 是否会有问题：
```bash
$ conda create -n testenv python=3.9 -y
$ conda activate testenv
$ pip install cnmaps ipython
```
然后打开 ipython 终端测试一下是否仍然复现

**Comment by ww15996472026** [comment]
虚拟环境里pip install cnmaps ipython报错了
```
(testenv) PS C:\Users\36404> pip install cnmaps ipython
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "D:\\anaconda\\Lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

**Comment by Clarmy** [comment]
最后经过沟通使用 windows 的  linux 子系统安装解决。
