### ISSUE TITLE
合并边界报错

### ISSUE THREAD

**Issue by hejiagail** [cnmetlab/cnmaps#110]
尝试合并边界：
beijing = get_adm_maps(province='北京市', only_polygon=True, record='first')
tianjin = get_adm_maps(province='天津市', only_polygon=True, record='first')
hebei = get_adm_maps(province='河北省', only_polygon=True, record='first')

jingjinji = beijing + tianjin + hebei
报错：
TypeError                                 Traceback (most recent call last)
Cell In[33], line 9
      6 tianjin = get_adm_maps(province='天津市', only_polygon=True, record='first')
      7 hebei = get_adm_maps(province='河北省', only_polygon=True, record='first')
----> 9 jingjinji = beijing + tianjin + hebei
     11 fig = plt.figure(figsize=(5,5))
     12 ax = fig.add_subplot(111, projection=ccrs.PlateCarree())

TypeError: unsupported operand type(s) for +: 'MultiPolygon' and 'MultiPolygon'

**Comment by Clarmy** [comment]
版本号是多少？

**Comment by hejiagail** [comment]
cnmaps 为1.1.0版本， python 是3.11

**Comment by Clarmy** [comment]
@hejiagail 升级到最新版本，用pip 安装： `pip install -U cnmaps`

**Comment by hejiagail** [comment]
好的，已解决，感谢🙏
