### ISSUE TITLE
如果要在一页多图里面使用cnmaps，只有最后一张图用了cnmaps

### ISSUE THREAD

**Issue by zhaolanxiai** [cnmetlab/cnmaps#28]

**Comment by Clarmy** [comment]
可以提供一下代码片段吗？如果有数据就更好了。

**Comment by hepengz** [comment]
from cnmaps import get_adm_maps, draw_maps
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

def plot_map(ax):
    draw_maps(get_adm_maps(province='河南省'), linewidth=0.3, color='k')
    return ax 

# Get the map projection information
cart_proj = ccrs.PlateCarree()

fig = plt.figure(figsize=(5, 5), dpi=300)

ax1 = fig.add_axes([0.13, 0.15, 0.5, 0.5], projection=cart_proj)
ax2 = fig.add_axes([0.13+0.65, 0.15, 0.5, 0.5], projection=cart_proj)

ax1 = plot_map(ax1)
ax2 = plot_map(ax2)

**Comment by hepengz** [comment]
from cnmaps import get_adm_maps, draw_maps
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

cart_proj = ccrs.PlateCarree()
fig = plt.figure(figsize=(5, 5), dpi=300)

ax1 = fig.add_axes([0.13, 0.15, 0.5, 0.5], projection=cart_proj)
draw_maps(get_adm_maps(province='河南省'), linewidth=0.3, color='k')

ax2 = fig.add_axes([0.13+0.65, 0.15, 0.5, 0.5], projection=cart_proj)
draw_maps(get_adm_maps(province='河南省'), linewidth=0.3, color='k')

**Comment by Clarmy** [comment]
调整一下绘制顺序：
```python
from cnmaps import get_adm_maps, draw_maps
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

def plot_map(ax):
    draw_maps(get_adm_maps(province='河南省'), linewidth=0.3, color='k')
    return ax

cart_proj = ccrs.PlateCarree()
fig = plt.figure(figsize=(5, 5), dpi=300)

ax1 = fig.add_axes([0.13, 0.15, 0.5, 0.5], projection=cart_proj)
ax1 = plot_map(ax1)

ax2 = fig.add_axes([0.13+0.65, 0.15, 0.5, 0.5], projection=cart_proj)
ax2 = plot_map(ax2)
```
![image](https://user-images.githubusercontent.com/20877876/182554490-e90b0d57-5ea0-48a7-8256-ac0a8affa501.png)
