### ISSUE TITLE
由于 shapely 版本问题导致的地图不正常

### ISSUE THREAD

**Issue by Clarmy** [cnmetlab/cnmaps#90]
按照 `conda install -c conda-forge cnmaps` 的方式进行安装以后，`get_adm_maps` 返回的结果不是 `MapPolygon` 类型。

**Comment by Clarmy** [comment]
降低 shapely 版本：`pip install shapely==1.8.5` 可以解决。

**Comment by myherocomeback** [comment]
FutureWarning: You are adding a column named 'geometry' to a GeoDataFrame constructed without an active geometry column. Currently, this automatically sets the active geometry column to 'geometry' but in the future that will no longer happen. Instead, either provide geometry to the GeoDataFrame constructor (GeoDataFrame(... geometry=GeoSeries()) or use `set_geometry('geometry')` to explicitly set the active geometry column.
  gdf["geometry"] = map_polygons
请问这个问题，也是通过降低shapely 版本可以解决吗？

**Comment by Clarmy** [comment]
@myherocomeback 这个警告的问题包括 shapely 版本的问题在 1.1.7 版本已经解决了，你可以 `pip install -U cnmaps` 更新版本（Python 解释器需要在3.9及以上）
