### ISSUE TITLE
cnmaps1.1.1版本  报“LLVM ERROR: Symbol not found: __svml_sin2_ha”错误

### ISSUE THREAD

**Issue by WilliamZcy** [cnmetlab/cnmaps#91]
采用pip安装cnmaps后，运行get_adm_maps（）后，会报“LLVM ERROR: Symbol not found: __svml_sin2_ha” 错误，目前是通过降级解决，1.0版本可正常运行。

**Comment by Clarmy** [comment]
有可能是numba的原因：https://github.com/lmcinnes/umap/issues/702
这里有一个解决方案可以尝试一下：https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093

**Comment by WilliamZcy** [comment]
解决方案有效，确实是这个原因，我的CPU是AMD的，现在用上最新版本了，非常感谢！ @Clarmy
