### ISSUE TITLE
clip时，当地图边界范围大于数据范围时会导致裁切后大范围留白，求问怎么解决

### ISSUE THREAD

**Issue by huddao** [cnmetlab/cnmaps#97]
裁切前：
![image](https://github.com/cnmetlab/cnmaps/assets/31430997/582d96a9-36aa-4683-88e9-9c5acf73c3b0)

裁切后会导致大范围留白：
![image](https://github.com/cnmetlab/cnmaps/assets/31430997/cdd6ebc3-4915-4a5b-92f0-8f1d11ae176e)
![image](https://github.com/cnmetlab/cnmaps/assets/31430997/5451ca21-7199-4864-ac21-3aa60670edb9)
找了很久都没解决，希望能帮忙看看是哪里的问题。

**Comment by Clarmy** [comment]
收到，我测试一下

**Comment by Clarmy** [comment]
你试一下这个样例：
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

from cnmaps import get_adm_maps, clip_contours_by_map, draw_maps, MapPolygon
from cnmaps.sample import load_temp
from shapely.geometry import Polygon

fig = plt.figure(figsize=(6, 5), dpi=300)
ax = fig.add_axes([0.1, 0.1, 0.8, 0.8], projection=ccrs.PlateCarree())
lons, lats, data = load_temp()
cs = ax.contourf(lons, lats, data)

boundary = MapPolygon(
    [Polygon([[70, 55], [140, 55], [140, 40], [70, 40], [70, 55]])]
) & get_adm_maps(country="中华人民共和国", only_polygon=True, record="first")

draw_maps(get_adm_maps(country="中华人民共和国"), ax)
clip_contours_by_map(cs, boundary, ax)
ax.set_extent([70, 140, 40, 55], crs=ccrs.PlateCarree())
fig.savefig("./test.png", bbox_inches="tight")
```
![test](https://github.com/cnmetlab/cnmaps/assets/20877876/cdd7fb37-38a1-42e0-b599-ba12c2c7d3b8)

**Comment by huddao** [comment]
感谢，完美解决

**Comment by huddao** [comment]
记录：可以通过ax的get_extent方法获取到边界，再通过`boundary = MapPolygon(
    [Polygon([[70, 55], [140, 55], [140, 40], [70, 40], [70, 55]])]
) & get_adm_maps(country="中华人民共和国", only_polygon=True, record="first")`的方法构建新的boundary用于裁切
